### ISSUE TITLE
Field Dependencies

### ISSUE THREAD

**Issue by amirsaffari** [podio/valideer#17]
Thanks for the fix last time around. Very appreciated.

I've another question which is about field dependencies and validation of them. Let me show this in an example:

```python
schema = {
  "addressCountry": "Country",
  "addressState": "State"
}
```

where *Country* is a validator that validates if an string is a country and normalizes it. Now validating *addressState* depends on the value of the normalized *addressCountry* field (i.e. you need to know the country to be able to validate if the state is correct or not).

So is there anyway in valideer to describe any such dependencies and for dependent validators to access the validated values of the dependent fields as input arguments?

Thanks again in advance.

**Comment by gsakkis** [comment]
There isn't a declarative way to describe dependencies but you can validate/adapt the whole structure after validating each field using `ChainOf`. It will look something like this:
```
field_schema = {
  "addressCountry": "Country",
  "addressState": "State"
}

COUNTRY_STATES = {
   ...
}

def validate_address(address):
    """Validate an address dict"""
    if address["addressState"] not in COUNTRY_STATES[address["addressCountry"]]:
        raise ValueError("Invalid state for country")
    return address

schema = valideer.ChainOf(
    field_schema, 
    valideer.AdaptBy(validate_address, ValueError)
)
```

**Comment by amirsaffari** [comment]
Thanks for the feedback. Yes, I can see now how this might work. Closing the issue now.
