### ISSUE TITLE
Union like properties support

### ISSUE THREAD

**Issue by ovanes** [podio/valideer#19]
Currently I don't find any support or possibility on how to validate that at least one of the properties in a dictionary should be present, e.g. smth like:

```python
"some_dictionary" :
AtLeastOneProperty
( { "my_key" : String()
  , "my_other_key" : Number()  
  }
)
```

**Comment by gsakkis** [comment]
There is `AnyOf`:  

	is_valid = valideer.AnyOf({"+my_key": "string"}, {"+my_other_key": "number"}).is_valid

	assert is_valid({"my_key": 12, "my_other_key": 3})
	assert is_valid({"my_key": "12", "my_other_key": "3"})
	assert is_valid({"my_key": "12"})
	assert is_valid({"my_other_key": 3})

	assert not is_valid({"my_key": 12, "my_other_key": "3"})
	assert not is_valid({"my_key": 12})
	assert not is_valid({"my_other_key": "3"})

**Comment by ovanes** [comment]
Yes, thanks that works just fine.
